/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FilterFrame.java
 *
 * Created on 18.08.2008, 22:30:01
 */

package filterapp;

import java.util.Date;
import javax.swing.table.TableModel;
import tdo.DataTable;
import tdo.bind.IPositionManager;
import tdo.bind.PositionManager;
import tdo.impl.Filterer;
import tdo.swing.model.ModelProvider;

/**
 *
 * @author Valery
 */
public class FilterFrame extends javax.swing.JFrame {

    /** Creates new form FilterFrame */
    public FilterFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        initTableButton = new javax.swing.JButton();
        filterButton1 = new javax.swing.JButton();
        filterButton2 = new javax.swing.JButton();
        cancelFilter1Button1 = new javax.swing.JButton();
        prepareFilterButton = new javax.swing.JButton();
        filterButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        initTableButton.setText("init Table");
        initTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initTableButtonActionPerformed(evt);
            }
        });

        filterButton1.setText("Filter1");
        filterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButton1ActionPerformed(evt);
            }
        });

        filterButton2.setText("Filter2");
        filterButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButton2ActionPerformed(evt);
            }
        });

        cancelFilter1Button1.setText("cancelFiler1");
        cancelFilter1Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFilter1Button1ActionPerformed(evt);
            }
        });

        prepareFilterButton.setText("prepareFilter");
        prepareFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prepareFilterButtonActionPerformed(evt);
            }
        });

        filterButton3.setText("Filter3");
        filterButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButton3ActionPerformed(evt);
            }
        });

        jTextField1.setText("1970-01-01");

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(initTableButton)
                    .addComponent(filterButton1)
                    .addComponent(filterButton2)
                    .addComponent(cancelFilter1Button1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prepareFilterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filterButton3))
                .addContainerGap(23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(initTableButton)
                        .addGap(18, 18, 18)
                        .addComponent(filterButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelFilter1Button1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prepareFilterButton)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DataTable persons;
    Filterer filterer1;
    Filterer filterer2;
    Filterer filterer3;

    private void initTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initTableButtonActionPerformed
        
        persons = new DataTable();
        IPositionManager pm = new PositionManager(persons);
        persons.getColumns().add(String.class, "FirstName") ;
        persons.getColumns().add(String.class,"LastName") ;
        persons.getColumns().add(Date.class,"birthDay");

        persons.getColumns().add(Date.class,"startDay");

        persons.addRow(new Object[] {"Tom", "Soyer", "1992-01-03", "2004-03-07"}  );
        persons.addRow( new Object[] {"Bill", "Gates", "1973-12-12", "1994-08-06"} );
        persons.addRow( new Object[] {"Tom", "Gates", "1969-11-13", "1990-07-05"} );
        persons.addRow( new Object[] {"Bob", "Stone", "1970-01-01", "1993-09-03"} );
        persons.addRow( new Object[] {"Tom", "Gates", "1968-11-13", "1988-07-05"} );
        persons.addRow( new Object[] {"Ann", "Stone", "1970-01-01", "1993-09-03"} );
        persons.addRow( new Object[] {"Ann", "Stone", "1982-01-01", "2003-11-03"} );
        persons.addRow( new Object[] {"Ann", "Stone", "1969-01-01", "1993-09-03"} );
        
        ModelProvider mp = new ModelProvider();
        TableModel model = mp.getTableModel(persons);
        this.jTable1.setModel(model);
        pm.add(this.jTextField2, "LastName");
        pm.add(jTable1);
        
        //this.filterButton2.setVisible(false);
        //this.cancelFilter1Button1.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_initTableButtonActionPerformed

    private void filterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButton1ActionPerformed
        filterer1 = persons.filter("birthDay >= '1970-01-01'");
    }//GEN-LAST:event_filterButton1ActionPerformed

    private void cancelFilter1Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFilter1Button1ActionPerformed
        persons.cancelFilter(filterer1);
    }//GEN-LAST:event_cancelFilter1Button1ActionPerformed

    private void filterButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButton2ActionPerformed
        filterer2 = persons.filter("firstName in('Tom','Ann')");
    }//GEN-LAST:event_filterButton2ActionPerformed

    private void prepareFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prepareFilterButtonActionPerformed
        filterer3 = persons.prepareFilter("birthDay >= :birth");
    }//GEN-LAST:event_prepareFilterButtonActionPerformed

    private void filterButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButton3ActionPerformed
        filterer3.setParameter("birth", this.jTextField1.getText());
        persons.filter(filterer3);
    }//GEN-LAST:event_filterButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelFilter1Button1;
    private javax.swing.JButton filterButton1;
    private javax.swing.JButton filterButton2;
    private javax.swing.JButton filterButton3;
    private javax.swing.JButton initTableButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton prepareFilterButton;
    // End of variables declaration//GEN-END:variables

}
