/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TdoSampleFrame.java
 *
 * Created on 27.08.2008, 11:54:06
 */

package tdosample;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import tdo.DataColumn;
import tdo.DataColumnCollection;
import tdo.DataRow;
import tdo.DataTable;
import tdo.EditObserver;
import tdo.TreeTable;
import tdo.bind.PositionManager;
import tdo.impl.TreeBuilder;
import tdo.persistence.LocalEditObserver;

/**
 *
 * @author valery
 */
public class TdoSampleFrame extends javax.swing.JFrame {
    EntityManager em;
    String persistenceUnitName = "TestTdoSampleAppPU";    
    DataTable depTable;
    int depId = 0;
    int emplId = 0;    
    DataTable emplTable;   
    PositionManager depPm;
    PositionManager emplPm;
    
    /** Creates new form TdoSampleFrame */
    public TdoSampleFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDepartment = new javax.swing.JTable();
        initButton1 = new javax.swing.JButton();
        addDepartmentButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmployee = new javax.swing.JTable();
        addEmployeeButton1 = new javax.swing.JButton();
        saveEmployeeButton1 = new javax.swing.JButton();
        createDb = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDepartment);

        initButton1.setText("Init");
        initButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initButton1ActionPerformed(evt);
            }
        });

        addDepartmentButton1.setText("Add");
        addDepartmentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDepartmentButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save Departments");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableEmployee);

        addEmployeeButton1.setText("Add");
        addEmployeeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButton1ActionPerformed(evt);
            }
        });

        saveEmployeeButton1.setText("Save Employee");

        createDb.setText("jButton1");
        createDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDbActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(initButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(createDb))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(addDepartmentButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(210, 210, 210))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(471, 471, 471)
                .addComponent(addEmployeeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188)
                .addComponent(saveEmployeeButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initButton1)
                    .addComponent(createDb))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDepartmentButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEmployeeButton1)
                    .addComponent(saveEmployeeButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(350, 350, 350))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initButton1ActionPerformed
        em = Persistence.createEntityManagerFactory(persistenceUnitName).createEntityManager();
        depTable = new DataTable(Department.class);
        EditObserver depObserver = new LocalEditObserver(depTable,em);
        depTable.setEditObserver(depObserver);
        depPm = new PositionManager(depTable);
        depPm.add(this.jTableDepartment);

        Query query = em.createQuery("SELECT d FROM Department d");
        List<Department> deps = query.getResultList();     
        depTable.populate(deps);
        DataColumn dc = depTable.getColumns().addCalculated(String.class, "myName");
        dc.setExpression("'dep'");


        DataTable dt = null;
        if ( depTable.getRowCount() > 0 ) {
            dt  = depTable.select("max(id) as maxId");
            depId = 1 + (Integer)dt.getRow(0).getValue("maxId");
        } else {
            depId = 0;
        }
        System.out.println("depId=" + depId);
        if ( depTable.getRowCount() > 0 ) {
            Department ro = depTable.getActiveRow().getObject();
            System.out.println("ro.name=" + ro.getName());
        }
        
        emplTable = depTable.createLinkedTable(Employee.class, "employeeCollection","department");
        EditObserver emplObserver = new LocalEditObserver(emplTable,em);
        emplTable.setEditObserver(emplObserver);
        
        emplPm =  new PositionManager(emplTable);
        emplPm.add(this.jTableEmployee);
        DataColumnCollection lcolumns = emplTable.getColumns();
        for ( int i=0; i < lcolumns.getCount(); i++ )
            System.out.println("name=" + lcolumns.get(i).getName() + ";  type=" + lcolumns.get(i).getType());

        DataTable edt = null;
        if ( emplTable.getRowCount() > 0 ) {
            edt  = emplTable.select("max(id) as maxId");
            emplId = 1 + (Integer)edt.getRow(0).getValue("maxId");
        } else {
            emplId = 0;
        }
        System.out.println("emplId=" + emplId);
        System.out.println("YES=" + em.contains(depTable.getRow(0).getObject() ) );
        em.getTransaction().begin();
        System.out.println("YES1=" + em.contains(depTable.getRow(0).getObject() ) );

    }//GEN-LAST:event_initButton1ActionPerformed

    private void addDepartmentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDepartmentButton1ActionPerformed
        DataRow depRow = depTable.addRow();
        //depRow.setValue(depId++, "id");
/*        if ( ! em.getTransaction().isActive() )
            em.getTransaction().begin();
        em.persist(depRow.getObject());
 */
    }//GEN-LAST:event_addDepartmentButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if ( ! em.getTransaction().isActive() )
            return;
        em.getTransaction().commit();
        em.getTransaction().begin();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addEmployeeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButton1ActionPerformed
        DataRow emplRow = emplTable.addRow();
        //emplRow.setValue(emplId++, "id");
        Department dep = depTable.getActiveRow().getObject();
        emplRow.setValue(dep,"department");        
/*        if ( ! em.getTransaction().isActive() )
            em.getTransaction().begin();
        em.persist(emplRow.getObject());
 */

    }//GEN-LAST:event_addEmployeeButton1ActionPerformed

    private void createDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDbActionPerformed
        TreeTable tt = depTable.createTreeTable("sum(id) as sumId", "myName",TreeBuilder.TOTALS_NONE,true);
        PositionManager pm = new PositionManager(tt);
        pm.add(this.jTable1);
    }//GEN-LAST:event_createDbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        em.getTransaction().begin();        
        em.persist(emplTable.getActiveRow().getObject());
        em.getTransaction().commit();        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TdoSampleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDepartmentButton1;
    private javax.swing.JButton addEmployeeButton1;
    private javax.swing.JButton createDb;
    private javax.swing.JButton initButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableDepartment;
    private javax.swing.JTable jTableEmployee;
    private javax.swing.JButton saveEmployeeButton1;
    // End of variables declaration//GEN-END:variables

}
