/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RelFrame.java
 *
 * Created on 19.08.2008, 12:06:02
 */
package relapp;

import java.math.BigDecimal;
import java.util.Date;
import tdo.DataTable;
import tdo.DataView;
import tdo.bind.PositionManager;

/**
 *
 * @author valery
 */
public class RelFrame extends javax.swing.JFrame {

    /** Creates new form RelFrame */
    public RelFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        initTablesButton1 = new javax.swing.JButton();
        setRelationButton2 = new javax.swing.JButton();
        stopRelationButton1 = new javax.swing.JButton();
        createViewButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        initTablesButton1.setText("init tables");
        initTablesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initTablesButton1ActionPerformed(evt);
            }
        });

        setRelationButton2.setText("Set Relation");
        setRelationButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRelationButton2ActionPerformed(evt);
            }
        });

        stopRelationButton1.setText("stop Relation");
        stopRelationButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopRelationButton1ActionPerformed(evt);
            }
        });

        createViewButton.setText("create View");
        createViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createViewButtonActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(initTablesButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(setRelationButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(stopRelationButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(createViewButton)))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(initTablesButton1)
                        .addGap(18, 18, 18)
                        .addComponent(setRelationButton2)
                        .addGap(18, 18, 18)
                        .addComponent(stopRelationButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(createViewButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DataTable customers;
    DataTable porders;
    PositionManager pm;
    PositionManager pm1;

    private void initTablesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initTablesButton1ActionPerformed
        customers = new DataTable();
        pm = new PositionManager(customers);
        customers.getColumns().add(Integer.class, "Customer_Id");
        customers.getColumns().add(String.class, "Name");
        customers.getColumns().add(String.class, "AddressLine1");
        customers.getColumns().add(String.class, "AddressLine2");
        customers.getColumns().add(String.class, "Zip");
        customers.getColumns().add(String.class, "City");
        customers.getColumns().add(String.class, "State");


        customers.addRow(new Object[]{1, "JumboCom", "111 E. Las Olas Blvd",
                    "Suite 51", "33015", "Fort Lauderdale", "FL"
                });
        customers.addRow(new Object[]{2, "Livermore Enterprises", "9754 Main Street",
                    "P.O. Box 567", "33055", "Miami", "FL"
                });
        customers.addRow(new Object[]{3, "Nano Apple", "8585 Murray Drive",
                    "P.O. Box 456", "12347", "Alanta", "GA"
                });

        pm.add(this.jTable1);


        porders = new DataTable();
        pm1 = new PositionManager(porders);
        porders.getColumns().add(Integer.class, "Order_Num");
        porders.getColumns().add(Integer.class, "Customer_Id");
        porders.getColumns().add(BigDecimal.class, "Shipping_Cost");
        porders.getColumns().add(Date.class, "Sales_Date");
        porders.getColumns().add(Date.class, "Shipping_Date");
        porders.getColumns().add(String.class, "Freight_Company");

        porders.addRow(new Object[]{10398001, 1, 449.00,
                    "2006-07-28", "2006-07-28", "Poney Express"});
        porders.addRow(new Object[]{10398002, 2, 359.99,
                    "2006-07-28", "2006-07-28", "Poney Express"});
        porders.addRow(new Object[]{10398003, 2, 275.00,
                    "2006-07-28", "2006-07-28", "Poney Express"});
        porders.addRow(new Object[]{10398004, 3, 275.00,
                    "2006-07-28", "2006-07-28", "Poney Express"});
        porders.addRow(new Object[]{10398005, 1, 459.00,
                    "2006-07-28", "2006-07-28", "Poney Express"});
        pm1.add(this.jTable2);            

    }//GEN-LAST:event_initTablesButton1ActionPerformed

    private void setRelationButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRelationButton2ActionPerformed
        porders.setRelation(customers, "Customer_Id", "Customer_Id");
    }//GEN-LAST:event_setRelationButton2ActionPerformed

    private void stopRelationButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopRelationButton1ActionPerformed
        porders.stopRelation();
    }//GEN-LAST:event_stopRelationButton1ActionPerformed

    private void createViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createViewButtonActionPerformed
        DataView dvporders = porders.createView();
        PositionManager dvpm = new PositionManager(dvporders);
        dvpm.add(this.jTable4);
        dvporders.setRelation(customers, "Customer_Id", "Customer_Id");

    }//GEN-LAST:event_createViewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createViewButton;
    private javax.swing.JButton initTablesButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton setRelationButton2;
    private javax.swing.JButton stopRelationButton1;
    // End of variables declaration//GEN-END:variables
}
