/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LTableFrame.java
 *
 * Created on 25.08.2008, 12:46:55
 */

package testlinked;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.swing.JTable;
import tdo.DataTable;
import tdo.LinkedDataTable;
import tdo.bind.PositionManager;

/**
 *
 * @author Valery
 */
public class LTableFrame extends javax.swing.JFrame {

    /** Creates new form LTableFrame */
    public LTableFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        purchaseOrderAddRow = new javax.swing.JButton();
        editAddedRowButton2 = new javax.swing.JButton();
        createEntityManagerButton2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Create Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        purchaseOrderAddRow.setText("Purch Order addRow");
        purchaseOrderAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseOrderAddRowActionPerformed(evt);
            }
        });

        editAddedRowButton2.setText("edit added row");
        editAddedRowButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAddedRowButton2ActionPerformed(evt);
            }
        });

        createEntityManagerButton2.setText("create Entity Manager");
        createEntityManagerButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEntityManagerButton2ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(createEntityManagerButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(122, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(purchaseOrderAddRow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editAddedRowButton2)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(createEntityManagerButton2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseOrderAddRow)
                    .addComponent(editAddedRowButton2))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    List<Customer> custList;
    DataTable dt;
    LinkedDataTable ldt;
    EntityManager em;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        custList = new ArrayList<Customer>();
        Customer cust = new Customer(1, 'A', "95000");
        custList.add(cust);
        cust = new Customer(2, 'B', "95001");
        custList.add(cust);
        cust = new Customer(3, 'C', "95002");
        custList.add(cust);
        dt = new DataTable(Customer.class);
        dt.populate(custList, Customer.class);
        ldt = dt.createLinkedTable(PurchaseOrder.class, "PurchaseOrderCollection");
        PositionManager pm = new PositionManager(dt);
        pm.add(this.jTable1);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
       //dt.populate(custList, Customer.class);
        PositionManager lpm = new PositionManager(ldt);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);        
        lpm.add(this.jTable2);
        System.out.println("0-clumn-type=" +ldt.getColumn(0).getType());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void purchaseOrderAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseOrderAddRowActionPerformed
        ldt.addRow();
    }//GEN-LAST:event_purchaseOrderAddRowActionPerformed

    private void editAddedRowButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAddedRowButton2ActionPerformed
        ldt.getRow(ldt.getActiveRowIndex()).endEdit();
    }//GEN-LAST:event_editAddedRowButton2ActionPerformed

    private void createEntityManagerButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEntityManagerButton2ActionPerformed
        em = Persistence.createEntityManagerFactory("TestLinkedTablePU").createEntityManager();
    }//GEN-LAST:event_createEntityManagerButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LTableFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createEntityManagerButton2;
    private javax.swing.JButton editAddedRowButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton purchaseOrderAddRow;
    // End of variables declaration//GEN-END:variables

}
