/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * db4oFrame.java
 *
 * Created on 22.08.2008, 14:51:41
 */
package testdb4o;

import JAppleLib.JAppleInc;
import JAppleLib.JAppleIno;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.util.List;
import tdo.DataTable;
import tdo.LinkedDataTable;
import tdo.bind.PositionManager;

/**
 *
 * @author valery
 */
public class db4oFrame extends javax.swing.JFrame {

    /** Creates new form db4oFrame */
    public db4oFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ObjectContainer db;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Db4o.configure().messageLevel(0);
            Db4o.configure().objectClass(JAppleLib.JAppleInc.class).cascadeOnActivate(true);
            Db4o.configure().objectClass(JAppleLib.JAppleInc.class).cascadeOnUpdate(true);
            Db4o.configure().objectClass(JAppleLib.JAppleInc.class).cascadeOnDelete(true);
            Db4o.configure().objectClass(JAppleLib.LinkedList.class).cascadeOnActivate(true);
            Db4o.configure().objectClass(JAppleLib.LinkedList.class).cascadeOnUpdate(true);
            Db4o.configure().objectClass(JAppleLib.LinkedList.class).cascadeOnDelete(true);
            db = Db4o.openFile("c:\\0\\from_SAGA_to_db4o.yap");
        } catch (Exception e) {
            System.out.println("Error On Activate");
        }
        JAppleInc testInc = new JAppleInc();
        ObjectSet os = db.get(testInc);
        DataTable dt = new DataTable(JAppleInc.class);
        PositionManager pm = new PositionManager(dt);
        dt.populate(os, JAppleInc.class);
        pm.add(this.jTable1);
        //this.jTable1.setAutoscrolls(true);
        this.jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
     
        LinkedDataTable ldt = dt.createLinkedTable(JAppleIno.class, "inos");
        PositionManager lpm = new PositionManager(ldt);
        lpm.add(jTable2);
        this.jTable2.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new db4oFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
